name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Deploy & Restart Bot
      run: |
        cd /home/discordbots/Jaseoke
        git reset --hard
        git pull origin master
        npm install
        pm2 restart Jaseoke
